name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release

    - uses: actions/upload-artifact@v2
      with:
        name: bee_names-${{ matrix.os }}
        path: |
          ./target/release/bee_names*
          !./target/release/bee_names.d
          !./target/release/bee_names.pdb
